### ISSUE TITLE
Firebase issue

### ISSUE THREAD

**Issue by OMGHaveFun** [LUGM/TechTatva-16#14]
@avikantz 
What about Terminating app due to uncaught exception 'com.firebase.core', reason: '[FIRApp configure] could not find a valid GoogleServices-Info.plist in your project. Please download one from https://console.firebase.google.com/.' error?

**Comment by avikantz** [comment]
That's due to missing firebase config, not an issue.

**Comment by avikantz** [comment]
Since this is fest app from last year, we won't be updating it anymore.
