### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by ykl7** [LUGM/TechTatva-16#7]

**Comment by anubhakushwaha** [comment]
@ykl7 Will do it .

**Comment by ykl7** [comment]
@anubhakushwaha please handle it then

**Comment by avikantz** [comment]
@anubhakushwaha Refer to http://github.com/LUGM/Revels-16 README for reference. Make appropriate changes.

**Comment by anubhakushwaha** [comment]
@ykl7  seems like I have to message you to get to know the whole app and further @avikantz the link that you provided says nothing about how other contributors can contribute,a project placed on github should be easily migrated to one's local machine easily and I guess that's what a readme does other than just info about the app.Anyways thanks for the help, I would add the following things in the README.md file:
Added:
1.Setup for Developers
2.Configuring remotes
3.Contributing and developing a feature
4.About the App
5.Add link to images stored in another folder and fb page.

**Comment by ykl7** [comment]
@anubhakushwaha the entire app is open sourced. Only API links and config files have been removed. They will not be a problem in documenting the app.

Your proposal seems good. Please do the needful. We are more than happy to answer any queries.
