### ISSUE TITLE
Refactor code.

### ISSUE THREAD

**Issue by avikantz** [LUGM/TechTatva-16#8]
Arrange the classes in both the folders and the Xcode project following MVC guidelines.

**Comment by OMGHaveFun** [comment]
@avikantz Hello. I want to help, the task is still relevant?

**Comment by avikantz** [comment]
@OMGHaveFun Sure

**Comment by OMGHaveFun** [comment]
Well, I'm starting

**Comment by OMGHaveFun** [comment]
@avikantz https://github.com/LUGM/TechTatva-16/pull/10

**Comment by OMGHaveFun** [comment]
@avikantz I can also fix the constraints if you create the appropriate issue
